# Generated by Django 4.0.6 on 2022-07-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_alter_task_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gmail_id',
            field=models.CharField(default='defaultid321', max_length=64),
            preserve_default=False,
        ),
    ]
