# Generated by Django 4.0.6 on 2022-08-01 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_alter_assign_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='being_assigned', to='frontpage.task'),
        ),
    ]
