# Generated by Django 4.0.6 on 2022-08-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_alter_assign_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='frontpage.task'),
        ),
    ]
