# Generated by Django 4.0.6 on 2022-08-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_alter_commenttask_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentdraft',
            options={'ordering': ['-time_commented']},
        ),
        migrations.AlterField(
            model_name='commentdraft',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='frontpage.draft'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drafted_for', to='frontpage.task'),
        ),
    ]
