# Generated by Django 4.0.6 on 2022-08-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0011_alter_commentdraft_options_alter_commentdraft_draft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='is_sent',
        ),
        migrations.DeleteModel(
            name='CommentDraft',
        ),
    ]
